/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import bd.Conexion;
import com.mysql.cj.jdbc.exceptions.SQLError;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author alumnoT
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        initVentana();
        initBD();
    }

    private void initVentana() {
        LocalDate hoy = LocalDate.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("EEEE dd/MM/yyyy");
        lblFecha.setText(hoy.format(formato));
        lblFecha1.setText(hoy.format(formato));
        lblFecha2.setText(hoy.format(formato));
        lblFecha3.setText(hoy.format(formato));
        lblFecha4.setText(hoy.format(formato));
        lblFecha5.setText(hoy.format(formato));
        lblFecha6.setText(hoy.format(formato));
        lblFecha7.setText(hoy.format(formato));
        LocalTime hora = LocalTime.now();
        DateTimeFormatter formato1 = DateTimeFormatter.ofPattern("HH:mm:ss");
        String sHora = hora.format(formato1);
        lblHora.setText(sHora);
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                LocalTime hora = LocalTime.now();
                DateTimeFormatter formato2 = DateTimeFormatter.ofPattern("HH:mm:ss");
                String sHora = hora.format(formato2);
                lblHora.setText(sHora);
                lblHora1.setText(sHora);
                lblHora2.setText(sHora);
                lblHora3.setText(sHora);
                lblHora4.setText(sHora);
                lblHora5.setText(sHora);
                lblHora6.setText(sHora);
                lblHora7.setText(sHora);
            }
        });
        timer.start();
    }

    private void initBD() {

        conexion = Conexion.mySQL("cajerojuanjo", "root", "");
        if (conexion == null) {
            JOptionPane.showMessageDialog(this, "Error, no se pudo conectar a la base de datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numeros = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        nulo1 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        nulo2 = new javax.swing.JButton();
        botones = new javax.swing.JPanel();
        btnRetroceder = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        operaciones = new javax.swing.JTabbedPane();
        Pantalla1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txfPin = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        Pantalla2 = new javax.swing.JPanel();
        acciones = new javax.swing.JPanel();
        btnIngreso = new javax.swing.JButton();
        btnRetiro = new javax.swing.JButton();
        btnTransferencia = new javax.swing.JButton();
        btnCambiarPIN = new javax.swing.JButton();
        btnConversion = new javax.swing.JButton();
        btnEstado = new javax.swing.JButton();
        lblFecha1 = new javax.swing.JLabel();
        lblHora1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        Pantalla3 = new javax.swing.JPanel();
        lblFecha2 = new javax.swing.JLabel();
        lblHora2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        IngresoCliente = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        IngresoConcepto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        IngresoImporte = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        IngresoCambiar = new javax.swing.JButton();
        IngresoConfirmar = new javax.swing.JButton();
        IngresoSalir = new javax.swing.JButton();
        Pantalla4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblFecha3 = new javax.swing.JLabel();
        lblHora3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RetiroImporte = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        RetiroCliente = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        RetiroCcc = new javax.swing.JButton();
        RetiroCsc = new javax.swing.JButton();
        RetiroCambiar = new javax.swing.JButton();
        RetiroSalir = new javax.swing.JButton();
        Pantalla5 = new javax.swing.JPanel();
        lblHora4 = new javax.swing.JLabel();
        lblFecha4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        CambioPA = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        CambioNP = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        CambioCP = new javax.swing.JTextField();
        CambioConfirmar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        CambioRealizar = new javax.swing.JButton();
        CambioSalir = new javax.swing.JButton();
        Pantalla6 = new javax.swing.JPanel();
        lblFecha5 = new javax.swing.JLabel();
        lblHora5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        TransferenciaIBAN = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TransferenciaConcepto = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TransferenciaCantidad = new javax.swing.JTextField();
        Pantalla7 = new javax.swing.JPanel();
        lblFecha6 = new javax.swing.JLabel();
        lblHora6 = new javax.swing.JLabel();
        Pantalla8 = new javax.swing.JPanel();
        lblFecha7 = new javax.swing.JLabel();
        lblHora7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        EstadoPropietario = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        EstadoSaldo = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        EstadoIBAN = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        EstadoFecha = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        EstadoImprimir = new javax.swing.JButton();
        EstadoCambio = new javax.swing.JButton();
        EstadoSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(800, 720));
        setPreferredSize(new java.awt.Dimension(800, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        numeros.setLayout(new java.awt.GridLayout(4, 0));

        btn1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        numeros.add(btn1);

        btn2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        numeros.add(btn2);

        btn3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        numeros.add(btn3);

        btn4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        numeros.add(btn4);

        btn5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        numeros.add(btn5);

        btn6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        numeros.add(btn6);

        btn7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        numeros.add(btn7);

        btn8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        numeros.add(btn8);

        btn9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        numeros.add(btn9);

        nulo1.setEnabled(false);
        numeros.add(nulo1);

        btn0.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        numeros.add(btn0);

        nulo2.setEnabled(false);
        numeros.add(nulo2);

        getContentPane().add(numeros);
        numeros.setBounds(116, 348, 280, 320);

        botones.setLayout(new java.awt.GridLayout(3, 0));

        btnRetroceder.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnRetroceder.setText("RETROCEDER");
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });
        botones.add(btnRetroceder);

        btnBorrar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBorrar.setText("BORRAR");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        botones.add(btnBorrar);

        btnConfirmar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        botones.add(btnConfirmar);

        getContentPane().add(botones);
        botones.setBounds(404, 348, 260, 320);

        Pantalla1.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Escribe el PIN:");

        txfPin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txfPin.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblFecha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblHora.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout Pantalla1Layout = new javax.swing.GroupLayout(Pantalla1);
        Pantalla1.setLayout(Pantalla1Layout);
        Pantalla1Layout.setHorizontalGroup(
            Pantalla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pantalla1Layout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addGroup(Pantalla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txfPin)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(324, 324, 324))
            .addGroup(Pantalla1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Pantalla1Layout.setVerticalGroup(
            Pantalla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pantalla1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pantalla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(lblHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(txfPin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        operaciones.addTab("Bienvenida", Pantalla1);

        acciones.setLayout(new java.awt.GridLayout(3, 0, 10, 10));

        btnIngreso.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnIngreso.setText("Ingreso");
        btnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoActionPerformed(evt);
            }
        });
        acciones.add(btnIngreso);

        btnRetiro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnRetiro.setText("Retiro");
        btnRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroActionPerformed(evt);
            }
        });
        acciones.add(btnRetiro);

        btnTransferencia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnTransferencia.setText("Transferencia");
        btnTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferenciaActionPerformed(evt);
            }
        });
        acciones.add(btnTransferencia);

        btnCambiarPIN.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCambiarPIN.setText("Cambiar PIN");
        btnCambiarPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarPINActionPerformed(evt);
            }
        });
        acciones.add(btnCambiarPIN);

        btnConversion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnConversion.setText("Conversion");
        btnConversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConversionActionPerformed(evt);
            }
        });
        acciones.add(btnConversion);

        btnEstado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEstado.setText("Estado de cuenta");
        btnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoActionPerformed(evt);
            }
        });
        acciones.add(btnEstado);

        lblFecha1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblHora1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnSalir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pantalla2Layout = new javax.swing.GroupLayout(Pantalla2);
        Pantalla2.setLayout(Pantalla2Layout);
        Pantalla2Layout.setHorizontalGroup(
            Pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pantalla2Layout.createSequentialGroup()
                .addGroup(Pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pantalla2Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(acciones, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pantalla2Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pantalla2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(lblHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(Pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Pantalla2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(680, Short.MAX_VALUE)))
        );
        Pantalla2Layout.setVerticalGroup(
            Pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pantalla2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(acciones, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(Pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Pantalla2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(266, Short.MAX_VALUE)))
        );

        operaciones.addTab("Operaciones", Pantalla2);

        lblFecha2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblHora2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jPanel12.setLayout(new java.awt.GridLayout(3, 0, 10, 0));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Cliente:");
        jPanel12.add(jLabel4);

        IngresoCliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        IngresoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel12.add(IngresoCliente);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Concepto:");
        jPanel12.add(jLabel7);

        IngresoConcepto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        IngresoConcepto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        IngresoConcepto.setBorder(null);
        jPanel12.add(IngresoConcepto);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Importe:");
        jPanel12.add(jLabel5);

        IngresoImporte.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        IngresoImporte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        IngresoImporte.setBorder(null);
        jPanel12.add(IngresoImporte);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("€");

        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        IngresoCambiar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        IngresoCambiar.setText("Cambiar Operación");
        IngresoCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoCambiarActionPerformed(evt);
            }
        });
        jPanel6.add(IngresoCambiar);

        IngresoConfirmar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        IngresoConfirmar.setText("Confirmar");
        IngresoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoConfirmarActionPerformed(evt);
            }
        });
        jPanel6.add(IngresoConfirmar);

        IngresoSalir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        IngresoSalir.setText("Salir");
        IngresoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoSalirActionPerformed(evt);
            }
        });
        jPanel6.add(IngresoSalir);

        javax.swing.GroupLayout Pantalla3Layout = new javax.swing.GroupLayout(Pantalla3);
        Pantalla3.setLayout(Pantalla3Layout);
        Pantalla3Layout.setHorizontalGroup(
            Pantalla3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pantalla3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pantalla3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pantalla3Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblHora2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pantalla3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Pantalla3Layout.setVerticalGroup(
            Pantalla3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pantalla3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pantalla3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Pantalla3Layout.createSequentialGroup()
                        .addGroup(Pantalla3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblHora2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(lblFecha2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        operaciones.addTab("Ingreso", Pantalla3);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Teclee el importe");

        lblFecha3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblHora3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Importe");

        RetiroImporte.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        RetiroImporte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel8.setText("€");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("(billetes de 10€, 20€ y de 50€)");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Cliente:");

        RetiroCliente.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        RetiroCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jPanel13.setLayout(new java.awt.GridLayout(4, 0, 0, 20));

        RetiroCcc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        RetiroCcc.setText("Confirmar con comprobante");
        jPanel13.add(RetiroCcc);

        RetiroCsc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        RetiroCsc.setText("Confirmar sin comprobante");
        jPanel13.add(RetiroCsc);

        RetiroCambiar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        RetiroCambiar.setText("Cambiar de Operación");
        RetiroCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetiroCambiarActionPerformed(evt);
            }
        });
        jPanel13.add(RetiroCambiar);

        RetiroSalir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        RetiroSalir.setText("Salir");
        RetiroSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetiroSalirActionPerformed(evt);
            }
        });
        jPanel13.add(RetiroSalir);

        javax.swing.GroupLayout Pantalla4Layout = new javax.swing.GroupLayout(Pantalla4);
        Pantalla4.setLayout(Pantalla4Layout);
        Pantalla4Layout.setHorizontalGroup(
            Pantalla4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pantalla4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pantalla4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pantalla4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHora3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RetiroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Pantalla4Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(Pantalla4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pantalla4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addGroup(Pantalla4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RetiroImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pantalla4Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        Pantalla4Layout.setVerticalGroup(
            Pantalla4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pantalla4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pantalla4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFecha3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(lblHora3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(Pantalla4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(RetiroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pantalla4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RetiroImporte, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pantalla4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        operaciones.addTab("Retiro", Pantalla4);

        lblHora4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblFecha4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jPanel2.setLayout(new java.awt.GridLayout(3, 0));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setText("PIN Actual:");
        jPanel2.add(jLabel18);

        CambioPA.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(CambioPA);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel19.setText("Nuevo PIN:");
        jPanel2.add(jLabel19);

        CambioNP.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(CambioNP);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel17.setText("Confirmar PIN:");
        jPanel2.add(jLabel17);

        CambioCP.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(CambioCP);

        CambioConfirmar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CambioConfirmar.setText("Confirmar");
        CambioConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambioConfirmarActionPerformed(evt);
            }
        });

        jPanel3.setLayout(new java.awt.GridLayout(2, 0, 0, 20));

        CambioRealizar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CambioRealizar.setText("Realizar otra operación");
        CambioRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambioRealizarActionPerformed(evt);
            }
        });
        jPanel3.add(CambioRealizar);

        CambioSalir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CambioSalir.setText("Salir");
        CambioSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambioSalirActionPerformed(evt);
            }
        });
        jPanel3.add(CambioSalir);

        javax.swing.GroupLayout Pantalla5Layout = new javax.swing.GroupLayout(Pantalla5);
        Pantalla5.setLayout(Pantalla5Layout);
        Pantalla5Layout.setHorizontalGroup(
            Pantalla5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pantalla5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(Pantalla5Layout.createSequentialGroup()
                .addGroup(Pantalla5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pantalla5Layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(CambioConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pantalla5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFecha4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHora4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Pantalla5Layout.setVerticalGroup(
            Pantalla5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pantalla5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pantalla5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFecha4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHora4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pantalla5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(CambioConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
        );

        operaciones.addTab("Cambio PIN", Pantalla5);

        lblFecha5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblHora5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setText("IBAN del destinatario");
        jPanel1.add(jLabel14);

        TransferenciaIBAN.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TransferenciaIBAN.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TransferenciaIBAN);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setText("Concepto");
        jPanel1.add(jLabel13);

        TransferenciaConcepto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TransferenciaConcepto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TransferenciaConcepto);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setText("€");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setText("Cantidad:");
        jLabel15.setMaximumSize(new java.awt.Dimension(64, 22));
        jLabel15.setMinimumSize(new java.awt.Dimension(64, 22));
        jLabel15.setPreferredSize(new java.awt.Dimension(64, 22));

        TransferenciaCantidad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TransferenciaCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout Pantalla6Layout = new javax.swing.GroupLayout(Pantalla6);
        Pantalla6.setLayout(Pantalla6Layout);
        Pantalla6Layout.setHorizontalGroup(
            Pantalla6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pantalla6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pantalla6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Pantalla6Layout.createSequentialGroup()
                        .addComponent(lblFecha5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHora5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pantalla6Layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TransferenciaCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );
        Pantalla6Layout.setVerticalGroup(
            Pantalla6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pantalla6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pantalla6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHora5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(Pantalla6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TransferenciaCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        operaciones.addTab("Transferencia", Pantalla6);

        lblFecha6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblHora6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout Pantalla7Layout = new javax.swing.GroupLayout(Pantalla7);
        Pantalla7.setLayout(Pantalla7Layout);
        Pantalla7Layout.setHorizontalGroup(
            Pantalla7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pantalla7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFecha6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHora6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(589, Short.MAX_VALUE))
        );
        Pantalla7Layout.setVerticalGroup(
            Pantalla7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pantalla7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pantalla7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFecha6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHora6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(266, Short.MAX_VALUE))
        );

        operaciones.addTab("Conversion", Pantalla7);

        lblFecha7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblHora7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jPanel4.setLayout(new java.awt.GridLayout(4, 0));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setText("Propietario:");
        jPanel4.add(jLabel20);

        EstadoPropietario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel4.add(EstadoPropietario);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel23.setText("Saldo actual:");
        jPanel4.add(jLabel23);

        EstadoSaldo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel4.add(EstadoSaldo);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel26.setText("IBAN:");
        jPanel4.add(jLabel26);

        EstadoIBAN.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel4.add(EstadoIBAN);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setText("Fecha:");
        jPanel4.add(jLabel21);

        EstadoFecha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel4.add(EstadoFecha);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 30, 0));

        EstadoImprimir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EstadoImprimir.setText("Imprimir");
        jPanel5.add(EstadoImprimir);

        EstadoCambio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EstadoCambio.setText("Cambiar Operacion");
        EstadoCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoCambioActionPerformed(evt);
            }
        });
        jPanel5.add(EstadoCambio);

        EstadoSalir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EstadoSalir.setText("Salir");
        EstadoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoSalirActionPerformed(evt);
            }
        });
        jPanel5.add(EstadoSalir);

        javax.swing.GroupLayout Pantalla8Layout = new javax.swing.GroupLayout(Pantalla8);
        Pantalla8.setLayout(Pantalla8Layout);
        Pantalla8Layout.setHorizontalGroup(
            Pantalla8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pantalla8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pantalla8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pantalla8Layout.createSequentialGroup()
                        .addComponent(lblFecha7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHora7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pantalla8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pantalla8Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        Pantalla8Layout.setVerticalGroup(
            Pantalla8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pantalla8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pantalla8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFecha7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHora7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
        );

        operaciones.addTab("Estado", Pantalla8);

        getContentPane().add(operaciones);
        operaciones.setBounds(0, 0, 800, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Teclado
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if (operaciones.getSelectedIndex() == 0) {
            txfPin.setText(txfPin.getText() + "1");
        } else if (operaciones.getSelectedIndex() == 2) {
            IngresoImporte.setText(IngresoImporte.getText() + "1");
        } else if (operaciones.getSelectedIndex() == 3) {
            RetiroImporte.setText(RetiroImporte.getText() + "1");
        }


    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        txfPin.setText(txfPin.getText() + "2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        txfPin.setText(txfPin.getText() + "3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        txfPin.setText(txfPin.getText() + "4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        txfPin.setText(txfPin.getText() + "5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        txfPin.setText(txfPin.getText() + "6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        txfPin.setText(txfPin.getText() + "7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        txfPin.setText(txfPin.getText() + "8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        txfPin.setText(txfPin.getText() + "9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        txfPin.setText(txfPin.getText() + "0");
    }//GEN-LAST:event_btn0ActionPerformed
    //Botones del teclado
    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        txfPin.setText("");
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        try {
            String pincogido = txfPin.getText();
            String modificado = pincogido.substring(0, pincogido.length() - 1);
            txfPin.setText(modificado);
        } catch (StringIndexOutOfBoundsException ex) {
        }
    }//GEN-LAST:event_btnRetrocederActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (operaciones.getSelectedIndex() == 0) {
            try {
                String sPin = txfPin.getText();
                sentencia = conexion.createStatement();
                String sql = "SELECT * FROM tarjetas WHERE pin=" + sPin + ";";
                resultado = sentencia.executeQuery(sql);
                if (resultado.next()) {
                    operaciones.setSelectedIndex(1);
                } else {
                    JOptionPane.showMessageDialog(this, "No hay ninguna tarjeta registrada con este pin", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            } catch (RuntimeException ex) {

            }
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoActionPerformed
        try {
            sentencia = conexion.createStatement();
            String sql1 = "SELECT propietario FROM tarjetas WHERE pin=" + txfPin.getText() + ";";
            resultado = sentencia.executeQuery(sql1);
            if (resultado.next()) {
                sentencia2 = conexion.createStatement();
                String sql2 = "SELECT nombre FROM clientes WHERE id=" + resultado.getString("propietario") + ";";
                resultado2 = sentencia2.executeQuery(sql2);
                if (resultado2.next()) {
                    IngresoCliente.setText(resultado2.getString("nombre"));
                }
            }
            operaciones.setSelectedIndex(2);

        } catch (SQLException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIngresoActionPerformed

    private void btnRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroActionPerformed
        try {
            sentencia = conexion.createStatement();
            String sql1 = "SELECT propietario FROM tarjetas WHERE pin=" + txfPin.getText() + ";";
            resultado = sentencia.executeQuery(sql1);
            if (resultado.next()) {
                sentencia2 = conexion.createStatement();
                String sql2 = "SELECT nombre FROM clientes WHERE id=" + resultado.getString("propietario") + ";";
                resultado2 = sentencia2.executeQuery(sql2);
                if (resultado2.next()) {
                    RetiroCliente.setText(resultado2.getString("nombre"));
                }
            }
            operaciones.setSelectedIndex(3);

        } catch (SQLException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRetiroActionPerformed

    private void btnTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferenciaActionPerformed
        operaciones.setSelectedIndex(5);
    }//GEN-LAST:event_btnTransferenciaActionPerformed

    private void btnCambiarPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarPINActionPerformed
        operaciones.setSelectedIndex(4);
        CambioCP.setText("");
        CambioNP.setText("");
        CambioPA.setText("");
    }//GEN-LAST:event_btnCambiarPINActionPerformed

    private void btnConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConversionActionPerformed
        operaciones.setSelectedIndex(6);
    }//GEN-LAST:event_btnConversionActionPerformed

    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoActionPerformed
        try {
            sentencia = conexion.createStatement();
            String sql1 = "SELECT propietario,saldo FROM tarjetas WHERE pin=" + txfPin.getText() + ";";
            resultado = sentencia.executeQuery(sql1);
            if (resultado.next()) {
                EstadoSaldo.setText(resultado.getString("saldo"));
                sentencia2 = conexion.createStatement();
                String sql2 = "SELECT nombre,IBAN FROM clientes WHERE id=" + resultado.getString("propietario") + ";";
                resultado2 = sentencia2.executeQuery(sql2);
                if (resultado2.next()) {
                    EstadoPropietario.setText(resultado2.getString("nombre"));
                    EstadoIBAN.setText(resultado2.getString("IBAN"));
                    LocalDate hoy = LocalDate.now();
                    DateTimeFormatter formato = DateTimeFormatter.ofPattern("EEEE, dd/MM/yyyy");
                    EstadoFecha.setText(hoy.format(formato));
                }
            }
            operaciones.setSelectedIndex(7);

        } catch (SQLException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEstadoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        txfPin.setText("");
        operaciones.setSelectedIndex(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void IngresoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoConfirmarActionPerformed

    }//GEN-LAST:event_IngresoConfirmarActionPerformed

    private void IngresoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoSalirActionPerformed
        txfPin.setText("");
        operaciones.setSelectedIndex(0);
    }//GEN-LAST:event_IngresoSalirActionPerformed

    private void RetiroSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetiroSalirActionPerformed
        txfPin.setText("");
        operaciones.setSelectedIndex(0);
    }//GEN-LAST:event_RetiroSalirActionPerformed

    private void CambioRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambioRealizarActionPerformed
        operaciones.setSelectedIndex(1);
    }//GEN-LAST:event_CambioRealizarActionPerformed

    private void CambioConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambioConfirmarActionPerformed
        try {
            if (CambioPA.getText().equals(txfPin.getText())) {
                if (CambioNP.getText().equals(CambioCP.getText())) {
                    int pinnuevo = Integer.parseInt(CambioNP.getText());
                    sentencia = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                    String sql = "SELECT * FROM tarjetas WHERE pin=" + CambioPA.getText() + ";";
                    resultado = sentencia.executeQuery(sql);
                    if (resultado.next()) {
                        resultado.updateInt("pin", pinnuevo);
                        resultado.updateRow();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "El PIN nuevo no coincide", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "El PIN actual es incorrecto", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
        } catch (NumberFormatException ex) {
        }
    }//GEN-LAST:event_CambioConfirmarActionPerformed

    private void CambioSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambioSalirActionPerformed
        txfPin.setText("");
        operaciones.setSelectedIndex(0);
    }//GEN-LAST:event_CambioSalirActionPerformed

    private void EstadoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoSalirActionPerformed
        txfPin.setText("");
        operaciones.setSelectedIndex(0);
    }//GEN-LAST:event_EstadoSalirActionPerformed

    private void EstadoCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoCambioActionPerformed
        EstadoPropietario.setText("");
        EstadoIBAN.setText("");
        EstadoFecha.setText("");
        EstadoSaldo.setText("");
        operaciones.setSelectedIndex(1);
    }//GEN-LAST:event_EstadoCambioActionPerformed

    private void RetiroCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetiroCambiarActionPerformed
        RetiroImporte.setText("");
        operaciones.setSelectedIndex(1);
    }//GEN-LAST:event_RetiroCambiarActionPerformed

    private void IngresoCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoCambiarActionPerformed
        IngresoConcepto.setText("");
        IngresoImporte.setText("");
        operaciones.setSelectedIndex(1);
    }//GEN-LAST:event_IngresoCambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CambioCP;
    private javax.swing.JButton CambioConfirmar;
    private javax.swing.JTextField CambioNP;
    private javax.swing.JTextField CambioPA;
    private javax.swing.JButton CambioRealizar;
    private javax.swing.JButton CambioSalir;
    private javax.swing.JButton EstadoCambio;
    private javax.swing.JLabel EstadoFecha;
    private javax.swing.JLabel EstadoIBAN;
    private javax.swing.JButton EstadoImprimir;
    private javax.swing.JLabel EstadoPropietario;
    private javax.swing.JLabel EstadoSaldo;
    private javax.swing.JButton EstadoSalir;
    private javax.swing.JButton IngresoCambiar;
    private javax.swing.JLabel IngresoCliente;
    private javax.swing.JTextField IngresoConcepto;
    private javax.swing.JButton IngresoConfirmar;
    private javax.swing.JTextField IngresoImporte;
    private javax.swing.JButton IngresoSalir;
    private javax.swing.JPanel Pantalla1;
    private javax.swing.JPanel Pantalla2;
    private javax.swing.JPanel Pantalla3;
    private javax.swing.JPanel Pantalla4;
    private javax.swing.JPanel Pantalla5;
    private javax.swing.JPanel Pantalla6;
    private javax.swing.JPanel Pantalla7;
    private javax.swing.JPanel Pantalla8;
    private javax.swing.JButton RetiroCambiar;
    private javax.swing.JButton RetiroCcc;
    private javax.swing.JLabel RetiroCliente;
    private javax.swing.JButton RetiroCsc;
    private javax.swing.JTextField RetiroImporte;
    private javax.swing.JButton RetiroSalir;
    private javax.swing.JTextField TransferenciaCantidad;
    private javax.swing.JTextField TransferenciaConcepto;
    private javax.swing.JTextField TransferenciaIBAN;
    private javax.swing.JPanel acciones;
    private javax.swing.JPanel botones;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCambiarPIN;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnConversion;
    private javax.swing.JButton btnEstado;
    private javax.swing.JButton btnIngreso;
    private javax.swing.JButton btnRetiro;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTransferencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFecha1;
    private javax.swing.JLabel lblFecha2;
    private javax.swing.JLabel lblFecha3;
    private javax.swing.JLabel lblFecha4;
    private javax.swing.JLabel lblFecha5;
    private javax.swing.JLabel lblFecha6;
    private javax.swing.JLabel lblFecha7;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblHora1;
    private javax.swing.JLabel lblHora2;
    private javax.swing.JLabel lblHora3;
    private javax.swing.JLabel lblHora4;
    private javax.swing.JLabel lblHora5;
    private javax.swing.JLabel lblHora6;
    private javax.swing.JLabel lblHora7;
    private javax.swing.JButton nulo1;
    private javax.swing.JButton nulo2;
    private javax.swing.JPanel numeros;
    private javax.swing.JTabbedPane operaciones;
    private javax.swing.JTextField txfPin;
    // End of variables declaration//GEN-END:variables
    Connection conexion;
    Statement sentencia;
    Statement sentenciatotal;
    Statement sentencia2;
    ResultSet resultado;
    ResultSet resultadototal;
    ResultSet resultado2;
}
