/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cajero;

import bd.Conexion;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author alumnoT
 */
public class estados extends javax.swing.JFrame {

    private Tarjeta t;
    private Cliente c;
    private operaciones operaciones;
    private bienvenidos bienvenidos;

    /**
     * Creates new form main
     */
    public estados(Tarjeta tarjeta, Cliente cliente) {
        initComponents();
        this.t = tarjeta;
        this.c = cliente;
        initVentana();
        initBD();
    }

    private boolean esNumero(String s1) {
        for (int i = 0; i < s1.length(); i++) {
            if (Character.isDigit(s1.charAt(i))) {
                return true;
            }
        }
        return false;
    }

    private void initVentana() {
        LocalDate hoy = LocalDate.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("EEEE dd/MM/yyyy");
        lblFecha1.setText(hoy.format(formato));
        lblFecha1.setText(hoy.format(formato));
        LocalTime hora = LocalTime.now();
        DateTimeFormatter formato1 = DateTimeFormatter.ofPattern("HH:mm:ss");
        String sHora = hora.format(formato1);
        lblHora1.setText(sHora);
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                LocalTime hora = LocalTime.now();
                DateTimeFormatter formato2 = DateTimeFormatter.ofPattern("HH:mm:ss");
                String sHora = hora.format(formato2);
                lblHora1.setText(sHora);
            }
        });
        timer.start();
        //introducir datos
        EstadoPropietario.setText(c.getNombre());
        EstadoIBAN.setText(c.getIBAN());
        EstadoSaldo.setText(t.getSaldo() + " €");
        DateTimeFormatter formato2 = DateTimeFormatter.ofPattern("EEEE, dd/MM/yyyy");
        EstadoFecha.setText(hoy.format(formato2));
        EstadoHora.setText(sHora);
    }

    private void initBD() {
        conexion = Conexion.mySQL("cajerojuanjo", "root", "");
        if (conexion == null) {
            JOptionPane.showMessageDialog(this, "Error, no se pudo conectar a la base de datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    private estados() {
        JOptionPane.showMessageDialog(this, "Error, debes iniciar sesion primero", "ERROR", JOptionPane.ERROR_MESSAGE);
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numeros = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        nulo1 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        nulo2 = new javax.swing.JButton();
        botones = new javax.swing.JPanel();
        btnRetroceder = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        lblFecha1 = new javax.swing.JLabel();
        lblHora1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        EstadoPropietario = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        EstadoIBAN = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        EstadoSaldo = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        EstadoFecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        EstadoHora = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        EstadoImprimir = new javax.swing.JButton();
        EstadoCambio = new javax.swing.JButton();
        EstadoSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(102, 102, 102));
        setLocation(new java.awt.Point(550, 140));
        setMinimumSize(new java.awt.Dimension(800, 720));
        setResizable(false);

        numeros.setLayout(new java.awt.GridLayout(4, 0));

        btn1.setFont(new java.awt.Font("Cascadia Code PL", 0, 36)); // NOI18N
        btn1.setText("1");
        numeros.add(btn1);

        btn2.setFont(new java.awt.Font("Cascadia Code PL", 0, 36)); // NOI18N
        btn2.setText("2");
        numeros.add(btn2);

        btn3.setFont(new java.awt.Font("Cascadia Code PL", 0, 36)); // NOI18N
        btn3.setText("3");
        numeros.add(btn3);

        btn4.setFont(new java.awt.Font("Cascadia Code PL", 0, 36)); // NOI18N
        btn4.setText("4");
        numeros.add(btn4);

        btn5.setFont(new java.awt.Font("Cascadia Code PL", 0, 36)); // NOI18N
        btn5.setText("5");
        numeros.add(btn5);

        btn6.setFont(new java.awt.Font("Cascadia Code PL", 0, 36)); // NOI18N
        btn6.setText("6");
        numeros.add(btn6);

        btn7.setFont(new java.awt.Font("Cascadia Code PL", 0, 36)); // NOI18N
        btn7.setText("7");
        numeros.add(btn7);

        btn8.setFont(new java.awt.Font("Cascadia Code PL", 0, 36)); // NOI18N
        btn8.setText("8");
        numeros.add(btn8);

        btn9.setFont(new java.awt.Font("Cascadia Code PL", 0, 36)); // NOI18N
        btn9.setText("9");
        numeros.add(btn9);

        nulo1.setEnabled(false);
        numeros.add(nulo1);

        btn0.setFont(new java.awt.Font("Cascadia Code PL", 0, 36)); // NOI18N
        btn0.setText("0");
        numeros.add(btn0);

        nulo2.setEnabled(false);
        numeros.add(nulo2);

        botones.setLayout(new java.awt.GridLayout(3, 0));

        btnRetroceder.setBackground(new java.awt.Color(255, 255, 51));
        btnRetroceder.setFont(new java.awt.Font("Cascadia Code PL", 0, 24)); // NOI18N
        btnRetroceder.setText("RETROCEDER");
        botones.add(btnRetroceder);

        btnBorrar.setBackground(new java.awt.Color(204, 0, 0));
        btnBorrar.setFont(new java.awt.Font("Cascadia Code PL", 0, 24)); // NOI18N
        btnBorrar.setText("BORRAR");
        botones.add(btnBorrar);

        btnConfirmar.setBackground(new java.awt.Color(51, 204, 0));
        btnConfirmar.setFont(new java.awt.Font("Cascadia Code PL", 0, 24)); // NOI18N
        btnConfirmar.setText("CONFIRMAR");
        botones.add(btnConfirmar);

        lblFecha1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblHora1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jPanel4.setLayout(new java.awt.GridLayout(5, 0));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setText("Propietario:");
        jPanel4.add(jLabel20);

        EstadoPropietario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel4.add(EstadoPropietario);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel26.setText("IBAN:");
        jPanel4.add(jLabel26);

        EstadoIBAN.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel4.add(EstadoIBAN);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel23.setText("Saldo actual:");
        jPanel4.add(jLabel23);

        EstadoSaldo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel4.add(EstadoSaldo);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setText("Fecha:");
        jPanel4.add(jLabel21);

        EstadoFecha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel4.add(EstadoFecha);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Hora:");
        jPanel4.add(jLabel1);

        EstadoHora.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel4.add(EstadoHora);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 30, 0));

        EstadoImprimir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EstadoImprimir.setText("Imprimir");
        EstadoImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoImprimirActionPerformed(evt);
            }
        });
        jPanel5.add(EstadoImprimir);

        EstadoCambio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EstadoCambio.setText("Cambiar Operacion");
        EstadoCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoCambioActionPerformed(evt);
            }
        });
        jPanel5.add(EstadoCambio);

        EstadoSalir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EstadoSalir.setText("Salir");
        EstadoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoSalirActionPerformed(evt);
            }
        });
        jPanel5.add(EstadoSalir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(numeros, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(botones, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numeros, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botones, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EstadoCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoCambioActionPerformed
        if (operaciones != null) {
            operaciones.setVisible(true);
            this.dispose();
        } else {
            operaciones = new operaciones(t, c);
            operaciones.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_EstadoCambioActionPerformed

    private void EstadoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoSalirActionPerformed
        if (bienvenidos != null) {
            bienvenidos.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Vuelva Pronto!!","HASTA LUEGO",JOptionPane.DEFAULT_OPTION);
            bienvenidos = new bienvenidos();
            bienvenidos.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_EstadoSalirActionPerformed

    private void EstadoImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoImprimirActionPerformed
        try {
            Paragraph texto,propietario, IBAN, saldo, fecha,pie,hora;
            Document documento = new Document();
            documento.setPageSize(PageSize.A6.rotate());
            PdfWriter writer = PdfWriter.getInstance(documento, new java.io.FileOutputStream("estado.pdf"));
            documento.open();
            Font fuente1 = new Font(FontFactory.getFont("arial", 13));
            Font fuente2 = new Font(FontFactory.getFont("arial", 18));
            Font fuente3 = new Font(FontFactory.getFont("arial", 9));
            fuente1.setStyle("bold");
            fuente2.setColor(BaseColor.BLUE);
            fuente3.setStyle("italic");
            texto=new Paragraph("Comprobante del Estado de la Cuenta",fuente2);
            documento.add(texto);
            propietario = new Paragraph("\nPropietario:     " + EstadoPropietario.getText(), fuente1);
            documento.add(propietario);
            IBAN = new Paragraph("IBAN:                " + EstadoIBAN.getText(), fuente1);
            documento.add(IBAN);
            saldo = new Paragraph("Saldo:               " + EstadoSaldo.getText(), fuente1);
            documento.add(saldo);
            fecha = new Paragraph("Fecha:              " + EstadoFecha.getText(), fuente1);
            documento.add(fecha);
            hora = new Paragraph("Hora:                " + EstadoHora.getText(), fuente1);
            documento.add(hora);
            pie = new Paragraph("\n\n\nGracias por su visita!!!",fuente3);
            documento.add(pie);
            
            File file = new File("estado.pdf");
            Desktop.getDesktop().open(file);
            documento.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(estados.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(estados.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(estados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EstadoImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(estados.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(estados.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(estados.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(estados.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new estados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EstadoCambio;
    private javax.swing.JLabel EstadoFecha;
    private javax.swing.JLabel EstadoHora;
    private javax.swing.JLabel EstadoIBAN;
    private javax.swing.JButton EstadoImprimir;
    private javax.swing.JLabel EstadoPropietario;
    private javax.swing.JLabel EstadoSaldo;
    private javax.swing.JButton EstadoSalir;
    private javax.swing.JPanel botones;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblFecha1;
    private javax.swing.JLabel lblHora1;
    private javax.swing.JButton nulo1;
    private javax.swing.JButton nulo2;
    private javax.swing.JPanel numeros;
    // End of variables declaration//GEN-END:variables
    Connection conexion;
    Statement sentencia;
    Statement sentencia2;
    ResultSet resultado;
    ResultSet resultado2;
    Tarjeta tarjeta;
    Cliente cliente;
}
